import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Experience from '../components/Experience'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'

const Home: NextPage = () => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0 ' >
      <Head>
        <title>Nader Elhaj</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />

      <section id='hero' className='snap-center'>
        <Hero />
      </section>

      {/* About */}
      <section id="about" className='snap-center'>
        <About />
      </section>

      {/* Experience */}

      <section id="experience" className='snap-center'>
        <Experience />
      </section>

      {/* Skills */}

      <section id="skills" className='snap-start'>
        <Skills />
      </section>

      {/* Projects */}

      <section id="projects" className='snap-start'>
        <Projects />
      </section>

      {/* Contact */}

      <section id="contact" className='snap-start'>
        <Contact />
      </section>

      
    </div>
  )
}

export default Home
