import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import About from '../components/About'
import Contact from '../components/Contact'
import Experience from '../components/Experience'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'

const Home: NextPage = () => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll z-0 overflow-x-hidden scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#f7ab0a]/40 ' >
      <Head>
        <title>Nader Elhaj</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />

      <section id='hero' className='snap-center'>
        <Hero />
      </section>

      {/* About */}
      <section id="about" className='snap-center'>
        <About />
      </section>

      {/* Experience */}

      <section id="experience" className='snap-center'>
        <Experience />
      </section>

      {/* Skills */}

      <section id="skills" className='snap-start'>
        <Skills />
      </section>

      {/* Projects */}

      <section id="projects" className='snap-start'>
        <Projects />
      </section>

      {/* Contact */}

      <section id="contact" className='snap-start pb-20'>
        <Contact />
      </section>
      <Link href={"#hero"} >
      <footer className='sticky bottom-5 w-full cursor-pointer'>
        <div className='flex items-center justify-center'>
          <img src="/images/me.jpg" alt="Avatar" className='w-10 h-10 rounded-full filter grayscale hover:grayscale-0 object-cover' />
        </div>
      </footer>
      </Link>

      
    </div>
  )
}

export default Home
